/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_mgmt_ncstate;


import java.util.*;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.*;

/**
 *
 * @author Isha
 */
public class Journals extends javax.swing.JFrame {

    /**
     * Creates new form Camera_module
     */
    static final String jdbcURL
            = "jdbc:oracle:thin:@ora.csc.ncsu.edu:1521:orcl";
    static Connection conn = null;
    static Statement stmt = null;
    static Statement stmt1 = null;
    static ResultSet rs = null;
    static String patron_id;

    public Journals(String id) {
        patron_id = id;
        initComponents();
        connect();
        load_journal_list();
    }

    public static void connect() {
        try {
            // Load the driver. This creates an instance of the driver
            // and calls the registerDriver method to make Oracle Thin
            // driver available to clients.
            Class.forName("oracle.jdbc.driver.OracleDriver");

            String user = "msaikia"; 	// For example, "jsmith"
            //String user = "ibobra";
            //String passwd = "200109140";	// Your 9 digit student ID number
            String passwd = "200109120";
                 // Get a connection from the first driver in the
            // DriverManager list that recognizes the URL jdbcURL
            conn = DriverManager.getConnection(jdbcURL, user, passwd);
		// Create a statement object that will be sending your
            // SQL statements to the DBMS
            stmt = conn.createStatement();
            stmt1 = conn.createStatement();

        } catch (Throwable oops) {
            oops.printStackTrace();
        } finally {
            close(rs);
                //close(stmt);
            //close(conn);
        }
    }

    public void load_journal_list() {
        DefaultListModel journallist = new DefaultListModel();
        DefaultListModel journallist2 = new DefaultListModel();
        try {
            rs = stmt.executeQuery("SELECT JOURNAL_ID FROM JOURNALLIST where is_available=1");
            while (rs.next()) {
                String journal_id = rs.getString("JOURNAL_ID");
                journallist.addElement(journal_id);
            }

            rs = stmt.executeQuery("SELECT journal_ID FROM journalLIST where is_available=0");
            while (rs.next()) {
                String book_id = rs.getString("JOURNAL_ID");
                journallist2.addElement(book_id);
            }
            jList1.setModel(journallist);
            jList3.setModel(journallist2);

        } catch (Throwable oops) {
            oops.printStackTrace();
        } finally {
            close(rs);
                //close(stmt);
            //close(conn);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setName("camer_frame"); // NOI18N
        setSize(new java.awt.Dimension(200, 150));

        jPanel1.setName("cmaera_panel"); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setName("camera_list"); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Journals");
        jLabel1.setName("CameraList_label"); // NOI18N

        jList2.setName("Camera_detail"); // NOI18N
        jScrollPane2.setViewportView(jList2);

        jButton1.setText("Request");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Click a journal id from the list to view the details");

        jLabel5.setText("Journal Details");
        jLabel5.setName("CameraList_label"); // NOI18N

        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList3);

        jLabel2.setText("Waitlist");

        jCheckBox1.setText("E-copy");

        jButton2.setText("Close");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(64, 64, 64))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        //int count = 0;
        String journal_id = (String) jList1.getSelectedValue();
        String journal_id2 = (String) jList3.getSelectedValue();
        try {
            if (journal_id != null) {
                rs = stmt.executeQuery("select issn from journallist where journal_id = '" + journal_id + "'");
                rs.next();
                String issn = rs.getString("issn");
                rs = stmt.executeQuery("Select r.patron_id from reservation r, journallist jl where r.resc_id=jl.journal_id and r.patron_id = '" + patron_id + "' and jl.issn = '" + issn + "'");
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "You have already reserved a copy of the journal");
                }
                else{
            //check for e-copy
            System.out.println("SELECT J.e_copy FROM JOURNALLIST JL, JOURNAL J where J.issn=jl.issn and jl.is_available=1 and jl.journal_id='"+journal_id+"'");
            rs = stmt1.executeQuery("SELECT J.e_copy FROM JOURNALLIST JL, JOURNAL J where J.issn=jl.issn and jl.is_available=1 and jl.journal_id='"+journal_id+"'");
                rs.next();
                    String ecopy = rs.getString("E_COPY");
            if(ecopy.equals("1") && jCheckBox1.isSelected())
            {
                JOptionPane.showMessageDialog(null, "E-copy has been reserved");
            }
            else if(ecopy.equals("0") && jCheckBox1.isSelected())
                {
                JOptionPane.showMessageDialog(null, "E-copy is not available");
            }
            
            else{
            int update_res = stmt.executeUpdate("insert into reservation(RES_ID,PATRON_ID,RESC_TYPE,RESC_ID,CHECKOUT_DATE) values(reservation_seq.nextval,'"+patron_id+"','Journal', '" + journal_id + "', SYSDATE)");
            int update_booklist = stmt1.executeUpdate("update journallist set is_available = 0 where journal_id='" + journal_id + "'");
            //rs = stmt.executeQuery("Commit");
            if (update_res > 0 && update_booklist > 0) {
                JOptionPane.showMessageDialog(null, "Journal has been reserved");
                load_journal_list();
            } else {
                JOptionPane.showMessageDialog(null, "Journal has not been reserved");
            }
            }
            }
            }
            
            else if(journal_id2 != null){ 
                
                rs=stmt.executeQuery("Select patron_id from resv_publ_q where patron_id = '"+patron_id+"' and publ_no = '"+journal_id2+"'");
                if(rs.next())
                    JOptionPane.showMessageDialog(null, "You are already in the queue for the book");
                else{
                    
                
                int update = stmt.executeUpdate("insert into resv_publ_q(publ_no,patron_id,req_date) values('"+journal_id2+"','"+patron_id+"', SYSDATE)");
              // System.out.println("Update value: "+update);
               if (update> 0) {
               JOptionPane.showMessageDialog(null, "You are in the queue for the journal");}
            //} else {
             //   JOptionPane.showMessageDialog(null, "Queuing not successful");
            //}
                }
            }
        } catch (Throwable oops) {
            oops.printStackTrace();
        } finally {
            close(rs);
            //close(stmt);
            //close(conn);
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        DefaultListModel journaldetail = new DefaultListModel();
        String journal_id = (String) jList1.getSelectedValue();
        try {
            rs = stmt.executeQuery("SELECT j.issn,j.title,j.author_name,j.publ_year,j.e_copy,l.lib_name"
                    + " FROM Journal j, library l where j.issn in(select j1.issn from Journal j1, Journallist jl where j1.issn=jl.issn and jl.lib_no=l.lib_no and jl.journal_id = '" + journal_id + "') ");
            journaldetail.clear();
            while (rs.next()) {
                String isbn = rs.getString("issn");
                String title = rs.getString("title");
                String author = rs.getString("author_name");
                //String edition = rs.getString("edition");
                String e_copy = rs.getBoolean("e_copy")?"Yes":"False";
                String publ_year = rs.getString("publ_year");
                String library_name = rs.getString("lib_name");
                journaldetail.addElement("ISSN: " + isbn);
                journaldetail.addElement("Title: " + title);
                journaldetail.addElement("Author Names: " + author);
                journaldetail.addElement("E-copy: " + e_copy );
                journaldetail.addElement("Published Year: " + publ_year);
                journaldetail.addElement("Library Name: " + library_name);
            }
            jList2.setModel(journaldetail);
        } catch (Throwable oops) {
            oops.printStackTrace();
        } finally {
            close(rs);
            //close(stmt);
            //close(conn);
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList3MouseClicked
        DefaultListModel journaldetail = new DefaultListModel();
        String journal_id = (String) jList3.getSelectedValue();
        try {
            rs = stmt.executeQuery("SELECT j.issn,j.title,j.author_name,j.publ_year,j.e_copy,l.lib_name"
                    + " FROM Journal j, library l where j.issn in(select j1.issn from Journal j1, Journallist jl where j1.issn=jl.issn and jl.lib_no=l.lib_no and jl.journal_id = '" + journal_id + "') ");
            journaldetail.clear();
            while (rs.next()) {
                String isbn = rs.getString("issn");
                String title = rs.getString("title");
                String author = rs.getString("author_name");
                String e_copy = rs.getBoolean("e_copy")?"Yes":"False";
                //String edition = rs.getString("edition");
                String publ_year = rs.getString("publ_year");
                String library_name = rs.getString("lib_name");
                journaldetail.addElement("ISSN: " + isbn);
                journaldetail.addElement("Title: " + title);
                journaldetail.addElement("Author Names: " + author);
                //bookdetail.addElement("Edition: " + edition );
                journaldetail.addElement("E-copy: " + e_copy );
                journaldetail.addElement("Published Year: " + publ_year);
                journaldetail.addElement("Library Name: " + library_name);
            }
            jList2.setModel(journaldetail);
        } catch (Throwable oops) {
            oops.printStackTrace();
        } finally {
            close(rs);
            //close(stmt);
            //close(conn);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jList3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    static void close(Connection conn) {
        if (conn != null) {
            try {
                conn.close();
            } catch (Throwable oops) {
                oops.printStackTrace();
            }
        }
    }

    static void close(Statement st) {
        if (st != null) {
            try {
                st.close();
            } catch (Throwable oops) {
                oops.printStackTrace();
            }
        }
    }

    static void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            } catch (Throwable oops) {
                oops.printStackTrace();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Journals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Journals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Journals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Journals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Journals(patron_id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
